version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommercedb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./server/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql:ro

  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ecommerce_server
    environment:
      - PORT=3000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=ecommercedb
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./:/usr/src/app # optional: mount project for live edits

volumes:
  db_data:
